-->> CURSOR EXPLICITO E TRADICIONAL

-->> cURSORES SE COMPORTAM COMO OS ARQUIVOS EM PYTHON
-->> ELES SÃO BASEADAS EM CONSULTA.
/*
1. DECLARACAO DO CURSOS
2. ABRIR O CURSOR
3. RECUPERAR LINHA A LINHA
4. FECHAMENTO
*/

DECLARE 
    CURSOR C_LIVRO IS
        SELECT LIVRO.TX_TITULO, AUTOR.NM_AUTOR FROM
        T_BS_AUTOR AUTOR INNER JOIN T_BS_LIVRO LIVRO ON
        (AUTOR.CD_AUTOR = LIVRO.CD_AUTOR);
        
    V_NMAUTOR T_BS_AUTOR.NM_AUTOR%TYPE;
    V_TXTITULO T_BS_LIVRO.TX_TITULO%TYPE;
    
    BEGIN
        OPEN C_LIVRO;
        LOOP
            FETCH C_lIVRO INTO V_TXTITULO, V_NMAUTOR;
            EXIT WHEN C_LIVRO%NOTFOUND;
            dbms_output.put_line('livro' || V_TXTITULO || ' autor: ' || V_NMAUTOR);
        END LOOP;
        CLOSE C_LIVRO;
    END;






/*
SELECT LIVRO.TX_TITULO, AUTOR.NM_AUTOR FROM
T_BS_AUTOR AUTOR INNER JOIN T_BS_LIVRO LIVRO ON
(AUTOR.CD_AUTOR = LIVRO.CD_AUTOR);*/
-->> FOR MAIS CURSOR
-->> CURSOR IMPLICITO
-->> CURSOR COM PARAMETRO