DECLARE 
QTDE T_BS_LIVRO_LIVRARIA.NR_QUANT%TYPE;
INICIAL INTEGER;
I INTEGER := 1;
BEGIN
INICIAL := SELECT COUNT(*)::INTEGER FROM T_BS_LIVRO_LIVRARIA;
FOR I IN 1..INICIAL
LOOP
SELECT SUM(NR_QUANT)
INTO QTDE
FROM T_BS_LIVRO_LIVRARIA
WHERE ROWNUM = I
GROUP BY CD_LIVRARIA, CD_CODIGO;
DBMS_OUTPUT.PUT_LINE(QTDE);
END LOOP;
EXCEPTION 
 WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('OCORREU UMA EXCEÇÃO ' || SQLERRM);
END;