-->> TRATAMENTO DE EXCEÇÃO
/*
SET SERVEROUTPUT ON;
DECLARE
    V_VALOR NUMBER := 70;
    V_QTD NUMBER := 0;
    MEDIA NUMBER;
BEGIN
    MEDIA := V_VALOR / V_QTD;
    DBMS_OUTPUT.PUT_LINE('A MÉDIA É '|| MEDIA);
    EXCEPTION
        WHEN ZERO_DIVIDE THEN
            DBMS_OUTPUT.PUT_LINE('NÃO É POSSIVEL DIVIDIR POR ZERO '|| SQLERRM);
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('OCORREU UMA EXCEÇÃO' || SQLERRM);
END;

*/
/*
-->> LANÇAMENTO DE EXCEÇÕES:
SET SERVEROUTPUT ON;
DECLARE
    V_VALOR NUMBER := -70;
    V_QTD NUMBER := 0;
    MEDIA NUMBER;
    QUANTIDADE_NEGATIVA EXCEPTION;
BEGIN
    IF V_VALOR < 0 OR V_QTD < 0 THEN
        RAISE QUANTIDADE_NEGATIVA;
    END IF;
    MEDIA := V_VALOR / V_QTD;
    DBMS_OUTPUT.PUT_LINE('A MÉDIA É '|| MEDIA);
    EXCEPTION
        WHEN QUANTIDADE_NEGATIVA THEN
            DBMS_OUTPUT.PUT_LINE(' A QUANTIDADE É NEGATIVA '|| SQLERRM);
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('OCORREU UMA EXCEÇÃO' || SQLERRM);
END;

*/


-->> LANÇANDO EXCEÇÕES USAND:
SET SERVEROUTPUT ON;
DECLARE
    V_VALOR NUMBER := -70;
    V_QTD NUMBER := 0;
    MEDIA NUMBER;
BEGIN
    IF V_VALOR < 0 OR V_QTD < 0 THEN
        RAISE_APPLICATION_ERROR(-2000, 'VALOR NEGATIVO');
    END IF;
    MEDIA := V_VALOR / V_QTD;
    DBMS_OUTPUT.PUT_LINE('A MÉDIA É '|| MEDIA);
    EXCEPTION
        WHEN ZERO_DIVIDE THEN
            DBMS_OUTPUT.PUT_LINE(' A QUANTIDADE É NEGATIVA '|| SQLERRM);
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('OCORREU UMA EXCEÇÃO ' || SQLERRM);
END;
